name: smooth_page_indicator
description: Customizable animated page indicator with a set of built-in effects.
version: 0.2.0
homepage: https://github.com/Milad-Akarie/smooth_page_indicator

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  preload_page_view: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
